language: node_js

node_js:
  - 'stable'
  - '4'
  - '0.10'

sudo: false

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install
  - npm update

cache:
  directories:
    - node_modules

os:
  - linux
  - osx

matrix:
  fast_finish: true

